
FROM docker.bintray.io/jfrog/artifactory-pro:latest

ADD ArtifactoryProInjector.jar ArtifactoryProInjector.jar

ENTRYPOINT exec java -jar ArtifactoryProInjector.jar /opt/jfrog/artifactory

# Key
# eyJwcm9kdWN0SWQiOjQsInByb2R1Y3ROYW1lIjoiQXJ0aWZhY3RvcnkgUHJvIiwidmFsaWRGcm9tIjoxNDc5OD
# UwNDMwNTcyLCJ2YWxpZFVudGlsIjoxNzk1MjEwNDMwNTczLCJxdWFudGl0eSI6MSwidHlwZSI6IkhBIiwiYXR0cmli
# dXRlcyI6eyJFTUFJTCI6IlI0UDMubmV0IiwiQ09NUEFOWSI6IlI0UDMubmV0IiwiTEFTVE5BTUUiOiJuZXQiLCJGSVJTVE5B
# TUUiOiJSNFAzIn19

